price = "platinum=19"

price = price.split('=')
price = int(price[1])
print(price)

print(("\033[48;2;" + ("32;49;55" if i % 2 == 0 else "16;22;25") +
           "m\033[38;2;60;135;156m" + list[1]  + ": " + str(list[0])) + "\033[0m" +
          f"    /w {list[1]} Yo, I want the '{item}' for {list[0]} Plat"
          ) #this color code was generated by AI (Could not learn it (: )

temp = lis[i][0]
lis[i][0] = lis[i][1]
lis[i][1] = temp